version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=mongodb://mongo/assignment2
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=assignment2
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
